/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"

#import "xkcm.h"

enum VersionStatus {
  VersionStatus_RECOMMENDED = 0,
  VersionStatus_COMPATIBLE = 1,
  VersionStatus_INCOMPATIBLE = 2
};

@interface VersionInfo : NSObject <NSCoding> {
  int __currentStatus;
  NSString * __currentMessage;
  NSString * __recommendedVersion;
  NSString * __linkUrl;

  BOOL __currentStatus_isset;
  BOOL __currentMessage_isset;
  BOOL __recommendedVersion_isset;
  BOOL __linkUrl_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=currentStatus, setter=setCurrentStatus:) int currentStatus;
@property (nonatomic, retain, getter=currentMessage, setter=setCurrentMessage:) NSString * currentMessage;
@property (nonatomic, retain, getter=recommendedVersion, setter=setRecommendedVersion:) NSString * recommendedVersion;
@property (nonatomic, retain, getter=linkUrl, setter=setLinkUrl:) NSString * linkUrl;
#endif

- (id) init;
- (id) initWithCurrentStatus: (int) currentStatus currentMessage: (NSString *) currentMessage recommendedVersion: (NSString *) recommendedVersion linkUrl: (NSString *) linkUrl;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int) currentStatus;
- (void) setCurrentStatus: (int) currentStatus;
#endif
- (BOOL) currentStatusIsSet;

#if !__has_feature(objc_arc)
- (NSString *) currentMessage;
- (void) setCurrentMessage: (NSString *) currentMessage;
#endif
- (BOOL) currentMessageIsSet;

#if !__has_feature(objc_arc)
- (NSString *) recommendedVersion;
- (void) setRecommendedVersion: (NSString *) recommendedVersion;
#endif
- (BOOL) recommendedVersionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) linkUrl;
- (void) setLinkUrl: (NSString *) linkUrl;
#endif
- (BOOL) linkUrlIsSet;

@end

@protocol AppService <NSObject>
- (VersionInfo *) validateVersion: (CommArgs *) commArgs;  // throws AuthException *, BizException *, TException
- (void) registerAPNSForIOS: (CommArgs *) commArgs deviceToken: (NSString *) deviceToken;  // throws AuthException *, BizException *, TException
- (void) cancelAPNSForIOS: (CommArgs *) commArgs deviceToken: (NSString *) deviceToken;  // throws AuthException *, BizException *, TException
@end

@interface AppServiceClient : NSObject <AppService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface AppServiceProcessor : NSObject <TProcessor> {
  id <AppService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithAppService: (id <AppService>) service;
- (id<AppService>) service;
@end

@interface appConstants : NSObject {
}
@end
