/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"

#import "xkcm.h"
#import "account.h"

@protocol FamilyService <NSObject>
- (void) updateFolkNickname: (CommArgs *) commArgs folkId: (NSString *) folkId callMe: (NSString *) callMe callTa: (NSString *) callTa;  // throws AuthException *, BizException *, TException
@end

@interface FamilyServiceClient : NSObject <FamilyService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface FamilyServiceProcessor : NSObject <TProcessor> {
  id <FamilyService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithFamilyService: (id <FamilyService>) service;
- (id<FamilyService>) service;
@end

@interface familyConstants : NSObject {
}
@end
