/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"

#import "xkcm.h"
#import "family.h"

enum UserGender {
  UserGender_MALE = 1,
  UserGender_FEMALE = 2
};

@interface UserInfo : NSObject <NSCoding> {
  NSString * __userId;
  NSString * __email;
  NSString * __mobileNum;
  NSString * __userName;
  NSString * __figureUrl;
  NSString * __birthday;
  int __gender;
  NSString * __telephone;
  NSString * __qq;

  BOOL __userId_isset;
  BOOL __email_isset;
  BOOL __mobileNum_isset;
  BOOL __userName_isset;
  BOOL __figureUrl_isset;
  BOOL __birthday_isset;
  BOOL __gender_isset;
  BOOL __telephone_isset;
  BOOL __qq_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=userId, setter=setUserId:) NSString * userId;
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, retain, getter=mobileNum, setter=setMobileNum:) NSString * mobileNum;
@property (nonatomic, retain, getter=userName, setter=setUserName:) NSString * userName;
@property (nonatomic, retain, getter=figureUrl, setter=setFigureUrl:) NSString * figureUrl;
@property (nonatomic, retain, getter=birthday, setter=setBirthday:) NSString * birthday;
@property (nonatomic, getter=gender, setter=setGender:) int gender;
@property (nonatomic, retain, getter=telephone, setter=setTelephone:) NSString * telephone;
@property (nonatomic, retain, getter=qq, setter=setQq:) NSString * qq;
#endif

- (id) init;
- (id) initWithUserId: (NSString *) userId email: (NSString *) email mobileNum: (NSString *) mobileNum userName: (NSString *) userName figureUrl: (NSString *) figureUrl birthday: (NSString *) birthday gender: (int) gender telephone: (NSString *) telephone qq: (NSString *) qq;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) userId;
- (void) setUserId: (NSString *) userId;
#endif
- (BOOL) userIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) mobileNum;
- (void) setMobileNum: (NSString *) mobileNum;
#endif
- (BOOL) mobileNumIsSet;

#if !__has_feature(objc_arc)
- (NSString *) userName;
- (void) setUserName: (NSString *) userName;
#endif
- (BOOL) userNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) figureUrl;
- (void) setFigureUrl: (NSString *) figureUrl;
#endif
- (BOOL) figureUrlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) birthday;
- (void) setBirthday: (NSString *) birthday;
#endif
- (BOOL) birthdayIsSet;

#if !__has_feature(objc_arc)
- (int) gender;
- (void) setGender: (int) gender;
#endif
- (BOOL) genderIsSet;

#if !__has_feature(objc_arc)
- (NSString *) telephone;
- (void) setTelephone: (NSString *) telephone;
#endif
- (BOOL) telephoneIsSet;

#if !__has_feature(objc_arc)
- (NSString *) qq;
- (void) setQq: (NSString *) qq;
#endif
- (BOOL) qqIsSet;

@end

@interface WatchInfo : NSObject <NSCoding> {
  BOOL __isBound;

  BOOL __isBound_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=isBound, setter=setIsBound:) BOOL isBound;
#endif

- (id) init;
- (id) initWithIsBound: (BOOL) isBound;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (BOOL) isBound;
- (void) setIsBound: (BOOL) isBound;
#endif
- (BOOL) isBoundIsSet;

@end

@protocol UserService <NSObject>
- (NSMutableArray *) searchUsers: (CommArgs *) commArgs condition: (NSString *) condition;  // throws AuthException *, BizException *, TException
- (ReturnMessage *) changeUserName: (CommArgs *) commArgs newUserName: (NSString *) newUserName;  // throws AuthException *, BizException *, TException
- (void) updateBirthday: (CommArgs *) commArgs userId: (NSString *) userId birthday: (NSString *) birthday;  // throws AuthException *, BizException *, TException
- (void) updateLocation: (CommArgs *) commArgs userId: (NSString *) userId districtCode: (NSString *) districtCode district: (NSString *) district;  // throws AuthException *, BizException *, TException
- (ReturnMessage *) setUserInfo: (CommArgs *) commArgs userInfo: (UserInfo *) userInfo;  // throws AuthException *, BizException *, TException
- (UserInfo *) getUserInfo: (CommArgs *) commArgs;  // throws AuthException *, BizException *, TException
- (WatchInfo *) getWatchInfo: (CommArgs *) commArgs userID: (NSString *) userID;  // throws AuthException *, BizException *, TException
@end

@interface UserServiceClient : NSObject <UserService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface UserServiceProcessor : NSObject <TProcessor> {
  id <UserService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithUserService: (id <UserService>) service;
- (id<UserService>) service;
@end

@interface userConstants : NSObject {
}
@end
